version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672

  mysql:
    image: mysql:latest
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    restart: unless-stopped
    ports:
      - 3306:3306

  review-app:
    build: ./
    image: review-app:1.0
    environment:
      RABBIT_UR: amqp://guest:guest@rabbit:5672
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      DB_NAME: adventureworks
      VALIDATE_QUEUE_NAME: validate
      NOTIFY_QUEUE_NAME: notify
      BAD_WORDS: fee,nee,cruul,leentdock
      DB_HOST: mysql
    restart: unless-stopped
    ports:
      - 8888:8888
    links:
      - rabbitmq:rabbitmq
      - mysql:mysql
    depends_on:
      - mysql
      - rabbitmq
